### ISSUE TITLE
Failed to start SDK on GM8136

### ISSUE THREAD

**Issue by csev1755** [OpenIPC/divinus#28]
Getting the following error when trying to run on a GM8136 and PS5230 sensor:

``` 
Divinus for grainmedia 
Chip ID: GM8136
[watchdog] Watchdog started!
[rtsp] Started listening for clients...
App built with headers v1.0
GrainMedia - library 0x41
IPCAM not support same cap channel/path to different h264
[err]   gm_bind (0x1, 0x76f88838, 0x76f88978):
        Invalid bindfd pointer.
There are ERRORs so it cannot APPLY, please EXIT application and check flow.
[err]   gm_apply groupfd(1):
        Apply fail!
[media] Binding channel 1 failed with 0x8100000b!
Unknown error code.
[media] MJPEG initialization failed with 0x1!
[hal] Failed to start SDK!

**Comment by wberube** [comment]
Good morning!

What is your current configuration for the mp4 and mjpeg sections in the .yaml file, and are you running the latest kernel+rootfs combo available for your camera?

Last I checked, I was able to have both streams enabled at the same time, but I don't have access to one of these right now to validate what could have gone wrong.

Keep me updated and I'll check what can be done in the meantime!

**Comment by csev1755** [comment]
Thanks for your quick response! I'm running the latest OpenIPC build, yes. Here's my configuration:

```
mp4:                          
  enable: true                
  codec: H264                                   
  mode: CBR                   
  width: 1920                                   
  height: 1080                                  
  fps: 20                                       
  gop: 40                                       
  bitrate: 1024               
  profile: 2                                    
                                                
jpeg:                                           
  enable: false                                 
  width: 1920                                   
  height: 1080                                  
  qfactor: 70          
                       
mjpeg:                 
  enable: true         
  mode: CBR            
  width: 1920          
  height: 1080 
  fps: 20
```
Disabling mjpeg does give me a video stream.
